server:
  port: 8080

spring:
  application:
    name: todo-kakao

  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/db?serverTimezone=Asia/Seoul
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create


    properties:
      hibernate.format_sql: true


    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true


# jwt 토큰 만들때 사용되는 비밀번호
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890

my:
  value: "welcome to my value"



